### ISSUE TITLE
Gives: Deprecated: Non-static method

### ISSUE THREAD

**Issue by Abdvkh** [thecodeholic/php-mvc-framework#1]
```

Deprecated: Non-static method app\models\User::primaryKey() should not be called statically in /Applications/XAMPP/xamppfiles/htdocs/php/mvc/core/Application.php on line 34

Deprecated: Non-static method app\core\DbModel::findOne() should not be called statically in /Applications/XAMPP/xamppfiles/htdocs/php/mvc/core/Application.php on line 35

Deprecated: Non-static method app\models\User::tableName() should not be called statically in /Applications/XAMPP/xamppfiles/htdocs/php/mvc/core/DbModel.php on line 34

```
Commit where you have created ```.findOne()``` function
https://github.com/thecodeholic/php-mvc-framework/commit/e9e01dd326b7c2a78b25e3e635340c2f4ee91f71

**Comment by NicolasHalberstadt** [comment]
Hi @Abdvkh, I'm in the same point as you and I apparently you can make your function static like that : 
`public static function findOne($where)`
and it will allow you to call it like that : 
`$this->userClass::findOne`
I don't know if that's the best option but it's working for me.

**Comment by Abdvkh** [comment]
@NicolasHalberstadt thanks for your help, i thought it will cause problems in the future, but I hope it's not so
