### ISSUE TITLE
After device restart, Completed Application cant find requested resource / on this server at localhost:8080

### ISSUE THREAD

**Issue by HoosierExperienceDesigner** [thecodeholic/php-mvc-framework#23]
After completing the application and getting it to work properly, I saved my progress and exited PHP Storm. 

I returned to stylize and add some additional features, but upon trying to run the app on localhost:8080 through the PHP storm's built-in server I get the following error: 

![Screenshot 2022-04-17 221043](https://user-images.githubusercontent.com/86378307/163743610-6919668c-7184-41da-af66-c4c8dd95015a.jpg)

However,  I can not navigate to 127.0.0.1 to see my root directory now. It just defaults to the XAMPP dashboard, and similarly, 127.0.0.1:8080 refuses to connect ... Does anyone have a hunch about why this is happening? 

localhost:8080 is returning a favicon with a 200 status code, from my Application's directory, but it's failing to route '/' to the home page. My hunch was that it is a composer or autoload related and I'm being very amateur and missing some configuration or initiation process upon restarting my computer and PHP Storm. 

Here's my composer.json config: 
![Screenshot 2022-04-18 000504](https://user-images.githubusercontent.com/86378307/163752767-3de09ae0-e854-4da8-aef7-b3889b819d07.jpg)

Still at a loss as to how to get this up and running correctly. Any help would be appreciated, as this has been a cool project to work on, and I want to understand my error here.

**Comment by RobertoVasquez01** [comment]
I don't use PHP storm and I can't help there.
I use sublime text with wamp which is similar to xamp.
What I did to avoid problems with routes are 2 things.

1. I created a Virtual Host directly to the folder that contains the entire app. In my case "C:\wamp64\www\p-opt\framework\ejm" (my virtual host is called framework.com )

2. Configure my .htaccess file. I share my configuration:
This file goes in the same root folder of the app.

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
#RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ public/index.php [QSA,L]
</IfModule>

With this, you just have to load framework.com and you're good to go.
NOTE: I don't think your .json file is the problem.

**Comment by thecodeholic** [comment]
@HoosierExperienceDesigner 
 I think you have started your application from the root directory of the project, but you should actually start from the public folder.
Just navigate into public folder of the project in terminal and then run `php -S localhost:8000` 
Or if you create a virtual host your DocumentRoot should be `{PATH_TO_YOUR_PROJECT}/public` folder.

**Comment by HoosierExperienceDesigner** [comment]
@thecodeholic You were right. How amateur of me! Thanks for your feedback - you saved me a lot of trouble.
