### ISSUE TITLE
How to avoid repeated code in each controller?

### ISSUE THREAD

**Issue by RobertoVasquez01** [thecodeholic/php-mvc-framework#27]
@thecodeholic. Thank you once again for this great contribution. Your tutorials are excellent. I would like to have an idea on the following:
The constructor of the AuthController class is responsible for registering each of the middleware. If I had 10 more controllers, and I didn't want to repeat the code in each constructor. What should I do?

1. Create a trait to register the middleware and use it only in the necessary controllers?
2. Move middleware registration to Core's Controller class constructor?... all controllers will be affected :-(
3. Replicate the AuthController class constructor code.

Have a nice day @thecodeholic

**Comment by thecodeholic** [comment]
Sorry for my late reply.
Don't like code duplication so I would not choose option 3.
Between 1st and 2nd options I think there is not better approach. Both of them are very similar.
Choose which one you prefer.
I am curious which option you have chosen.

**Comment by RobertoVasquez01** [comment]
I chose the first one and the trait works very well. I'm calm because after doing it, I found that Laravel does something similar in its controllers.
Following your php-mvc-framework project helped me understand many concepts.
By the way, do you use Eloquent? Which ORM is your favourite?
