### ISSUE TITLE
Solution to " Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, non-static method app\controllers\SiteController::contact() cannot be called statically" error during the implementation of the controller

### ISSUE THREAD

**Issue by araragi-koyomi-sama** [thecodeholic/php-mvc-framework#3]
hello, i'm using php 8.x, i solved this problem making static every function in SiteController (where i had to use SiteController), based on the documentation in the version 8.x the operator :: is used for static functions, i also had to use use app\core\Application in the SiteController to include Application in SiteController. I write down this here just in the case other one had the same problem. (sorry for my english, I'm not a native speaker)

**Comment by araragi-koyomi-sama** [comment]
also, if someone find a solution to this kind of problems whitout making the functions statics I'm looking forward to heard about it

**Comment by onabright** [comment]
Hi guys, I am also using PHP 8.x and I had to declare my functions as static to resolve the error: Uncaught TypeError: call_user_func(). Hopefully I will figure out how to do it without using static methods.

**Comment by AlanSMat** [comment]
Thank you @karam-mustafa, that worked for me.

**Comment by eisa97** [comment]
> you can solve problem by make new instance from this class, like this
> 
> ```
> 
> $app->router->get('/about', [AboutController::class, 'index']); // from this
> 
> $app->router->get('/about', [new AboutController(), 'index']); // to this
> ```

hi
thank you; but if how i can implement $app->router->get('/about', [AboutController::class, 'index']), because use this  on a tutorial movie. but do not work for me.

**Comment by none-08** [comment]
> you can solve problem by make new instance from this class, like this
> 
> ```
> 
> $app->router->get('/about', [AboutController::class, 'index']); // from this
> 
> $app->router->get('/about', [new AboutController(), 'index']); // to this
> ```

**Thanks a lot**, i was trying to solve this for about 6 hours and i was about to give up

**Comment by Mouhamed120** [comment]
[::1]:62171 [500]: GET /products/create - Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, non-static method app\controllers\ProductController::create() cannot be called statically in C:\xampp\htdocs\learn_php\01_theholicod\15-autoloading\better\Router.php:35
Stack trace:
#0 C:\xampp\htdocs\learn_php\01_theholicod\15-autoloading\better\Router.php(35): call_user_func()
#1 C:\xampp\htdocs\learn_php\01_theholicod\15-autoloading\better\public\index.php(19): app\Router->resolve()
#2 {main}
  thrown in C:\xampp\htdocs\learn_php\01_theholicod\15-autoloading\better\Router.php on line 35
Help

**Comment by Mouhamed120** [comment]
I think the problem is solved but I have not tested
===============  
$app->router->get('/about', [AboutController::class, 'index']); // from this

$app->router->get('/about', [new AboutController(), 'index']); // to this

**Comment by imManish** [comment]
you can solve this by checking if your callback is_array or string 
```php
if(is_array($callback))
     $callback[0] = new $callback[0];
 //var_dump($callback);
 return call_user_func($callback);
```

**Comment by frankndungu** [comment]
This worked for me. 

$app->router->get('/about', [AboutController::class, 'index']); // from this

$app->router->get('/about', [new AboutController(), 'index']); // to this

**Comment by MajedHasan** [comment]
> you can solve problem by make new instance from this class, like this
> 
> ```
> 
> $app->router->get('/about', [AboutController::class, 'index']); // from this
> 
> $app->router->get('/about', [new AboutController(), 'index']); // to this
> ```

Thank you for sharing this with us :)
But can you please tell me why this issue is happening?

**Comment by frankndungu** [comment]
The error has to do with your php version, when I downgraded to 7.4 the first option worked well but if you are on php 8^ it won't work

**Comment by frankndungu** [comment]
The error has to do with your php version, when I downgraded to 7.4 the
first option worked well but if you are on php 8^ it won't work

**Comment by kapasulediesel5** [comment]
> I use php 8.* as well and I had the same problem. because I liked the way we write our route , I changed my _**resolve**_ method in **_Router_** class.
> 
> I called the function like this: `return call_user_func([new $callback[0],$callback[1]]);`

could you please paste full code?
