### ISSUE TITLE
Cannot Find Core Folder 

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [thecodeholic/php-mvc-framework#6]
Hello @thecodeholic I have been following your tutorial. But I cannot find the core folder within this repo. Can you please share with us where the folder is? As it is very important all the main classes are there.

Also I want to keep track of the changes you have made after each video.

Thank you .

**Comment by tanjir-mahabub** [comment]
You will get core folder inside the vendor/thecodeholic folder. Thank you.

**Comment by thecodeholic** [comment]
Here is the core package which is installed in the framework using composer. 
https://github.com/thecodeholic/tc-php-mvc-core

The code will be available at `vendor/thecodeholic/php-mvc-core` after you run the composer install from the project.
